name: 'Qualify'

on:
  push:
  pull_request:

concurrency:
  group: 'qualify-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  qualify:
    name: qualify
    runs-on: semversie-runner
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Install Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm install
      - name: run tests
        run: npm test

  formatting:
    name: Check code formatting
    runs-on: semversie-runner
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Install Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: '24'
      - name: setup dependencies
        timeout-minutes: 5
        run: npm install
      - name: check formatting
        run: npm run format
      - name: verify no formatting changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Code is not properly formatted. Please run 'npm run format' and commit the changes.";
            exit 1;
          else
            echo "Code is properly formatted.";
          fi
